### ISSUE TITLE
Please review week 7

### ISSUE THREAD

**Issue by priteshshah1983** [MyChallenger/Challenger#23]
Please review week 7 changes. /cc @codepathreview @codepath

We have two roles: Challenger Poster (for self) and Challenge Backer. I created a playlist on YouTube:

Hopefully it all makes sense to you :)

https://www.youtube.com/playlist?list=PLt6Lo4rBYDaIW91MrWSJGAQWXTGG173No

**Comment by codepathreview** [comment]
:+1: Nice work so far on the group project. Your team has made great progress in the last week. Hope you are proud of what you have achieved in ~6 weeks.
- Consider taking actions on the review comments and please create [issues/milestones](https://github.com/MyChallenger/Challenger/milestones) for each of your sprint. Also, make sure that the tasks are equally distributed and assigned to the respective team members.
- Make sure that all the members of the team are equally [contributing](https://github.com/MyChallenger/Challenger/graphs/contributors) to your project.
- Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place.
- Try to challenge yourself on the UI/visual side of things in the coming days. Not necessarily flashy things, but it's the small details that take a lot of work.
- Keep working on integrating the core flows and make sure all pieces fit together perfectly.
- Consult with your mentors to get their feedback as often as you can. Remember they are here to help!
- While working on polishing your app for next sprint, remember that your app follows the [android design guidelines](http://guides.codepath.com/android/Android-Design-Guidelines) and also benchmark your app on sites such as [android app patterns](http://www.android-app-patterns.com/) to improve the UI/UX.

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week!
