### ISSUE TITLE
Implement list open challenges screen

### ISSUE THREAD

**Issue by priteshshah1983** [MyChallenger/Challenger#3]
HomeScreen can be fragmented into 2 timelines, One to view the challenges timeline another tab to view the stream of top challenges that were completed and videos or photos associated with it. 

Challenges timeline has list of challenges that are still open and user can back.

**Comment by vrumale** [comment]
![challenger](https://cloud.githubusercontent.com/assets/9405213/6545407/fe6907a2-c542-11e4-91a6-02ee0e9fac55.gif)
